INSERT INTO literal VALUES(SEQ_LITERAL.nextval , 'pizzeria-answered', 'welcomeMessage','Welcome to our pizzeria! This is Joanna, how can I help you today?', 'waitress welcome message');
INSERT INTO literal VALUES(SEQ_LITERAL.nextval , 'pizzeria-answered', 'pizzaPickedMessage',' looks nice.', 'waitress reaction to picking pizza');
INSERT INTO literal VALUES(SEQ_LITERAL.nextval , 'pizzeria-answered', 'additionMessage','Great! Do you want to pick some extras to your pizza?', 'waitress asking for additions');
INSERT INTO literal VALUES(SEQ_LITERAL.nextval , 'pizzeria-answered', 'additionPickedMessage','I would choose it too!', 'waitress message after addition picked');
INSERT INTO literal VALUES(SEQ_LITERAL.nextval , 'pizzeria-answered', 'additionNotPickedMessage','Oki-doki!', 'waitress message after no addition picked');
INSERT INTO literal VALUES(SEQ_LITERAL.nextval , 'pizzeria-answered', 'addressMessage','What address should we deliver to?', 'waitress asking for the delivery address');
INSERT INTO literal VALUES(SEQ_LITERAL.nextval , 'write-address', 'saveButton','Save', 'button save address');
INSERT INTO literal VALUES(SEQ_LITERAL.nextval , 'write-address', 'nameRequired','Name is required', 'name required field');
INSERT INTO literal VALUES(SEQ_LITERAL.nextval , 'write-address', 'phoneRequired','Phone is required', 'phone required field');
INSERT INTO literal VALUES(SEQ_LITERAL.nextval , 'write-address', 'streetRequired','Street is required', 'street required field');
INSERT INTO literal VALUES(SEQ_LITERAL.nextval , 'write-address', 'buildingRequired','Building is required', 'building required field');
INSERT INTO literal VALUES(SEQ_LITERAL.nextval , 'write-address', 'cityRequired','City is required', 'city required field');
INSERT INTO literal VALUES(SEQ_LITERAL.nextval , 'write-address', 'zipCodeRequired','Zip code is required', 'zip code required field');
INSERT INTO literal VALUES(SEQ_LITERAL.nextval , 'thank-you', 'orderConfirmed','Thank you!<br />Your order has been <span class="text-orange">confirmed.</span>', 'order confirmed innerHtml message');
INSERT INTO literal VALUES(SEQ_LITERAL.nextval , 'thank-you', 'orderCancelled','Thank you!<br />Your order has been <span class="text-orange">cancelled.</span>', 'order cancelled innerHTML message');
INSERT INTO literal VALUES(SEQ_LITERAL.nextval , 'thank-you', 'confirmOrder','Confirm your order:', 'confirm order message');
INSERT INTO literal VALUES(SEQ_LITERAL.nextval , 'thank-you', 'itemColumn','Item:', 'column item name');
INSERT INTO literal VALUES(SEQ_LITERAL.nextval , 'thank-you', 'quantityColumn','Quantity:', 'column quantity name');
INSERT INTO literal VALUES(SEQ_LITERAL.nextval , 'thank-you', 'priceColumn','Price:', 'column price name');
INSERT INTO literal VALUES(SEQ_LITERAL.nextval , 'thank-you', 'totalMessage','Total:', 'message near total amount to pay');
INSERT INTO literal VALUES(SEQ_LITERAL.nextval , 'thank-you', 'orderButton','Order now', 'order now button');
INSERT INTO literal VALUES(SEQ_LITERAL.nextval , 'thank-you', 'cancelButton','Cancel', 'cancel button');
